image: registry.code.fbi.h-da.de/db2-praktikum/base-project/dependency_image:latest

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle
  - chmod +x ./gradlew
  - cp -r /dependencies/.gradle ./
  - cp -r /dependencies/build ./

stages:
  - create_dependency_image
  - build
  - check

build:
  stage: build
  script:
    - ./gradlew assemble

checkstyle_main:
  stage: check
  script:
    - ./gradlew checkstyleMain -x test
    - cp build/reports/checkstyle/main.html ./checkstyleMain.html
  artifacts:
    paths:
      - checkstyleMain.html
    expire_in: 1 week

checkstyle_test:
  stage: check
  script:
    - ./gradlew checkstyleTest -x test
    - cp build/reports/checkstyle/test.html ./checkstyleTest.html
  artifacts:
    paths:
      - checkstyleTest.html
    expire_in: 1 week

spotbugs_main:
  stage: check
  script:
    - ./gradlew spotbugsMain -x test
  after_script:
    - cp build/reports/spotbugs/main.html ./spotbugsMain.html
  artifacts:
    when: always
    paths:
      - spotbugsMain.html
    expire_in: 1 week

spotbugs_test:
  stage: check
  script:
    - ./gradlew spotbugsTest -x test
    - cp build/reports/spotbugs/test.html ./spotbugsTest.html
  artifacts:
    paths:
      - spotbugsTest.html
    expire_in: 1 week


# create_dependency_image:
#   stage: create_dependency_image
#   image:
#     name: gcr.io/kaniko-project/executor:debug
#     entrypoint: [""]
#   script:
#     - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
#     - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/docker/dependencyImage/Dockerfile --destination $CI_REGISTRY_IMAGE/dependency_image:latest
#   when: manual
#   only:
#     - dependencyImage