/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import de.h_da.fbi.db2.stud.Main;
import org.junit.Test;
import static org.junit.Assert.*;

public class MainTest {
    @Test public void testMainHasAGreeting() {
        Main classUnderTest = new Main();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
}
